### PR TITLE
Rotate

### PR DESCRIPTION
**Pull request by sdaoden**
On top of

  https://github.com/troglobit/sysklogd/pull/45

(merge conflicts otherwise) here is the forced-rotation patch again.
Here too i have split out the test, which is untouched for 24 months.

### CODE REVIEW

**Comment by sdaoden** [comment]
Hm. Second github pull request ever. Here rotate is on top of notify, but.. well. Sorry for that, dunno how to split it via github, but of course one needs notify to not have merge conflicts anyhow.

**Comment by troglobit** [comment]
LGTM, except for the test code, see the first PR for test changes required.  Nice work!

**Comment by sdaoden** [comment]
Thanks!  I have updated the test accordingly.

**Comment by troglobit** [comment]
Rebased and merged manually to master.

**Pull request closed without merging**
